version: '3.3'

services:
  eventstore:
    image: eventstore/eventstore:release-5.0.1
    volumes:
      - es_data:/var/lib/eventstore
    ports:
      - '1113:1113'
      - '2113:2113'
    environment:
      - RUN_PROJECTIONS=All
  redis:
    image: redis:4.0.9
    ports:
      - '6379:6379'
volumes:
  es_data:
